type Section {
  professor: Professor
  class: Class
  students: Int!
  rating: Float
  comments: [String]
}

type Class {
  identifier: String!
  course_num: Int!
  full_identifier: String! @unique
  name: String
  department: String
  description: String
  credit_hours: String
  sections: [Section] @relation(name: "section_relation")
  professors: [Professor] @relation(name: "class_relation")
}

type Professor {
  first: String!
  last: String!
  full_name: String!
  bio: String
  sections: [Section] @relation(name: "section_relation")
  classes: [Class!] @relation(name: "class_relation")
}

type Query {
  allProfessors: [Professor!]
  allSections: [Section!]
  allClasses: [Class!]
  classesByNum(course_num: Int!): [Class!]
  classesByFullIdentifier(full_identifier: String!): Class
  classesByDepartmentAbbrev()
}
