type Section {
  professor: Professor
  students: Int!
  class: Class
  rating: Float!
  comments: [String]
}

type Class {
  identifier: String!
  courseNum: Int!
  fullIdentifier: String! @unique
  sections: [Section] @relation(name: "section_relation")
  professors: [Professor] @relation(name: "class_relation")
}

type Professor {
  first: String!
  last: String!
  sections: [Section] @relation(name: "section_relation")
  classes: [Class!] @relation(name: "class_relation")
}

type Query {
  allProfessors: [Professor!]
  allSections: [Section!]
  allClasses: [Class!]
  classesByNum(courseNum: Int!): [Class!]
  classesByFullIdentifier(fullIdentifier: String!): Class
}
